### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/formio-builder#104]
The Roadmap for the formio-builder library/project.

Core functionality

- [x] Sort out type definitions for all component types (`@open-formulieren/types`)
- [x] Implement all component types edit form
- [ ] Implement new design - component library to use to be specified. May come with a sass-toolchain.

Builder UI

- [ ] Sidebar/component type picker, grouped into categories
- [ ] Dropzone to drop a picked component
- [ ] Dropzone for container components (fieldset, columns, editgrid...) to support child/nested components

Editors:

- [ ] Use a more clever approach for rich-text editing, with first-class support for Django template variables/filters/tags (Slate.js looks interesting)
- [ ] Set up a better JSON-data/templates editor (Slate.js based too?)
